package cn.com.ccyw.mapper;

import cn.com.ccyw.entity.Linkuser;

public interface LinkuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkuser
     *
     * @mbg.generated
     */
    int insert(Linkuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkuser
     *
     * @mbg.generated
     */
    int insertSelective(Linkuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkuser
     *
     * @mbg.generated
     */
    Linkuser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Linkuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Linkuser record);
}