package cn.com.ccyw.mapper;

import cn.com.ccyw.entity.YxCcywHttpStatus;

public interface YxCcywHttpStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_http_status
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String statusid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_http_status
     *
     * @mbg.generated
     */
    int insert(YxCcywHttpStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_http_status
     *
     * @mbg.generated
     */
    int insertSelective(YxCcywHttpStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_http_status
     *
     * @mbg.generated
     */
    YxCcywHttpStatus selectByPrimaryKey(String statusid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_http_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YxCcywHttpStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_http_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YxCcywHttpStatus record);
}