package cn.com.ccyw.entity;

public class Depart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.departname
     *
     * @mbg.generated
     */
    private String departname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.pdepartid
     *
     * @mbg.generated
     */
    private String pdepartid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.id
     *
     * @return the value of depart.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.id
     *
     * @param id the value for depart.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.departname
     *
     * @return the value of depart.departname
     *
     * @mbg.generated
     */
    public String getDepartname() {
        return departname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.departname
     *
     * @param departname the value for depart.departname
     *
     * @mbg.generated
     */
    public void setDepartname(String departname) {
        this.departname = departname == null ? null : departname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.pdepartid
     *
     * @return the value of depart.pdepartid
     *
     * @mbg.generated
     */
    public String getPdepartid() {
        return pdepartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.pdepartid
     *
     * @param pdepartid the value for depart.pdepartid
     *
     * @mbg.generated
     */
    public void setPdepartid(String pdepartid) {
        this.pdepartid = pdepartid == null ? null : pdepartid.trim();
    }
}