package cn.com.ccyw.entity;

import java.util.Date;

public class YxCcywHttpStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_http_status.statusid
     *
     * @mbg.generated
     */
    private String statusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_http_status.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_http_status.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_http_status.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_http_status.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_http_status.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_http_status.statusid
     *
     * @return the value of yx_ccyw_http_status.statusid
     *
     * @mbg.generated
     */
    public String getStatusid() {
        return statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_http_status.statusid
     *
     * @param statusid the value for yx_ccyw_http_status.statusid
     *
     * @mbg.generated
     */
    public void setStatusid(String statusid) {
        this.statusid = statusid == null ? null : statusid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_http_status.date
     *
     * @return the value of yx_ccyw_http_status.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_http_status.date
     *
     * @param date the value for yx_ccyw_http_status.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_http_status.message
     *
     * @return the value of yx_ccyw_http_status.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_http_status.message
     *
     * @param message the value for yx_ccyw_http_status.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_http_status.status
     *
     * @return the value of yx_ccyw_http_status.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_http_status.status
     *
     * @param status the value for yx_ccyw_http_status.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_http_status.city
     *
     * @return the value of yx_ccyw_http_status.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_http_status.city
     *
     * @param city the value for yx_ccyw_http_status.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_http_status.count
     *
     * @return the value of yx_ccyw_http_status.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_http_status.count
     *
     * @param count the value for yx_ccyw_http_status.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}