package cn.com.ccyw.wechat.manager.mapper.weather;

import cn.com.ccyw.wechat.manager.entity.weather.YxCcywWeatherData;

import java.util.List;

public interface YxCcywWeatherDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_weather_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String dataid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_weather_data
     *
     * @mbg.generated
     */
    int insert(YxCcywWeatherData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_weather_data
     *
     * @mbg.generated
     */
    int insertSelective(YxCcywWeatherData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_weather_data
     *
     * @mbg.generated
     */
    YxCcywWeatherData selectByPrimaryKey(String dataid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_weather_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YxCcywWeatherData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_weather_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YxCcywWeatherData record);

    /**
     * 批量插入数据
     * @param records
     * @return
     */
    int batchInsert(List<YxCcywWeatherData> records);
}