package cn.com.ccyw.wechat.manager.mapper.weather;

import cn.com.ccyw.wechat.manager.entity.weather.YxCcywWeatherDatatitle;

public interface YxCcywWeatherDatatitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_weather_datatitle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String datatitleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_weather_datatitle
     *
     * @mbg.generated
     */
    int insert(YxCcywWeatherDatatitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_weather_datatitle
     *
     * @mbg.generated
     */
    int insertSelective(YxCcywWeatherDatatitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_weather_datatitle
     *
     * @mbg.generated
     */
    YxCcywWeatherDatatitle selectByPrimaryKey(String datatitleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_weather_datatitle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YxCcywWeatherDatatitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yx_ccyw_weather_datatitle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YxCcywWeatherDatatitle record);

    /**
     * 通过statusid查询数据
     * @param statusid
     * @return
     */
    YxCcywWeatherDatatitle selectByStatusId(String statusid);
}