package cn.com.ccyw.wechat.manager.entity.weather;

import java.io.Serializable;

public class YxCcywWeatherData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_data.dataid
     *
     * @mbg.generated
     */
    private String dataid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_data.statusid
     *
     * @mbg.generated
     */
    private String statusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_data.date
     *
     * @mbg.generated
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_data.sunrise
     *
     * @mbg.generated
     */
    private String sunrise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_data.high
     *
     * @mbg.generated
     */
    private String high;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_data.low
     *
     * @mbg.generated
     */
    private String low;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_data.sunset
     *
     * @mbg.generated
     */
    private String sunset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_data.aqi
     *
     * @mbg.generated
     */
    private Integer aqi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_data.fx
     *
     * @mbg.generated
     */
    private String fx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_data.fl
     *
     * @mbg.generated
     */
    private String fl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_data.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_data.notice
     *
     * @mbg.generated
     */
    private String notice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_data.dataid
     *
     * @return the value of yx_ccyw_weather_data.dataid
     *
     * @mbg.generated
     */
    public String getDataid() {
        return dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_data.dataid
     *
     * @param dataid the value for yx_ccyw_weather_data.dataid
     *
     * @mbg.generated
     */
    public void setDataid(String dataid) {
        this.dataid = dataid == null ? null : dataid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_data.statusid
     *
     * @return the value of yx_ccyw_weather_data.statusid
     *
     * @mbg.generated
     */
    public String getStatusid() {
        return statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_data.statusid
     *
     * @param statusid the value for yx_ccyw_weather_data.statusid
     *
     * @mbg.generated
     */
    public void setStatusid(String statusid) {
        this.statusid = statusid == null ? null : statusid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_data.date
     *
     * @return the value of yx_ccyw_weather_data.date
     *
     * @mbg.generated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_data.date
     *
     * @param date the value for yx_ccyw_weather_data.date
     *
     * @mbg.generated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_data.sunrise
     *
     * @return the value of yx_ccyw_weather_data.sunrise
     *
     * @mbg.generated
     */
    public String getSunrise() {
        return sunrise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_data.sunrise
     *
     * @param sunrise the value for yx_ccyw_weather_data.sunrise
     *
     * @mbg.generated
     */
    public void setSunrise(String sunrise) {
        this.sunrise = sunrise == null ? null : sunrise.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_data.high
     *
     * @return the value of yx_ccyw_weather_data.high
     *
     * @mbg.generated
     */
    public String getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_data.high
     *
     * @param high the value for yx_ccyw_weather_data.high
     *
     * @mbg.generated
     */
    public void setHigh(String high) {
        this.high = high == null ? null : high.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_data.low
     *
     * @return the value of yx_ccyw_weather_data.low
     *
     * @mbg.generated
     */
    public String getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_data.low
     *
     * @param low the value for yx_ccyw_weather_data.low
     *
     * @mbg.generated
     */
    public void setLow(String low) {
        this.low = low == null ? null : low.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_data.sunset
     *
     * @return the value of yx_ccyw_weather_data.sunset
     *
     * @mbg.generated
     */
    public String getSunset() {
        return sunset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_data.sunset
     *
     * @param sunset the value for yx_ccyw_weather_data.sunset
     *
     * @mbg.generated
     */
    public void setSunset(String sunset) {
        this.sunset = sunset == null ? null : sunset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_data.aqi
     *
     * @return the value of yx_ccyw_weather_data.aqi
     *
     * @mbg.generated
     */
    public Integer getAqi() {
        return aqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_data.aqi
     *
     * @param aqi the value for yx_ccyw_weather_data.aqi
     *
     * @mbg.generated
     */
    public void setAqi(Integer aqi) {
        this.aqi = aqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_data.fx
     *
     * @return the value of yx_ccyw_weather_data.fx
     *
     * @mbg.generated
     */
    public String getFx() {
        return fx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_data.fx
     *
     * @param fx the value for yx_ccyw_weather_data.fx
     *
     * @mbg.generated
     */
    public void setFx(String fx) {
        this.fx = fx == null ? null : fx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_data.fl
     *
     * @return the value of yx_ccyw_weather_data.fl
     *
     * @mbg.generated
     */
    public String getFl() {
        return fl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_data.fl
     *
     * @param fl the value for yx_ccyw_weather_data.fl
     *
     * @mbg.generated
     */
    public void setFl(String fl) {
        this.fl = fl == null ? null : fl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_data.type
     *
     * @return the value of yx_ccyw_weather_data.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_data.type
     *
     * @param type the value for yx_ccyw_weather_data.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_data.notice
     *
     * @return the value of yx_ccyw_weather_data.notice
     *
     * @mbg.generated
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_data.notice
     *
     * @param notice the value for yx_ccyw_weather_data.notice
     *
     * @mbg.generated
     */
    public void setNotice(String notice) {
        this.notice = notice == null ? null : notice.trim();
    }
}