package cn.com.ccyw.wechat.manager.entity.weather;

public class YxCcywWeatherDatatitle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_datatitle.datatitleid
     *
     * @mbg.generated
     */
    private String datatitleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_datatitle.statusid
     *
     * @mbg.generated
     */
    private String statusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_datatitle.shidu
     *
     * @mbg.generated
     */
    private String shidu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_datatitle.pm25
     *
     * @mbg.generated
     */
    private Integer pm25;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_datatitle.pm10
     *
     * @mbg.generated
     */
    private Integer pm10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_datatitle.quality
     *
     * @mbg.generated
     */
    private String quality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_datatitle.wendu
     *
     * @mbg.generated
     */
    private String wendu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yx_ccyw_weather_datatitle.ganmao
     *
     * @mbg.generated
     */
    private String ganmao;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_datatitle.datatitleid
     *
     * @return the value of yx_ccyw_weather_datatitle.datatitleid
     *
     * @mbg.generated
     */
    public String getDatatitleid() {
        return datatitleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_datatitle.datatitleid
     *
     * @param datatitleid the value for yx_ccyw_weather_datatitle.datatitleid
     *
     * @mbg.generated
     */
    public void setDatatitleid(String datatitleid) {
        this.datatitleid = datatitleid == null ? null : datatitleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_datatitle.statusid
     *
     * @return the value of yx_ccyw_weather_datatitle.statusid
     *
     * @mbg.generated
     */
    public String getStatusid() {
        return statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_datatitle.statusid
     *
     * @param statusid the value for yx_ccyw_weather_datatitle.statusid
     *
     * @mbg.generated
     */
    public void setStatusid(String statusid) {
        this.statusid = statusid == null ? null : statusid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_datatitle.shidu
     *
     * @return the value of yx_ccyw_weather_datatitle.shidu
     *
     * @mbg.generated
     */
    public String getShidu() {
        return shidu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_datatitle.shidu
     *
     * @param shidu the value for yx_ccyw_weather_datatitle.shidu
     *
     * @mbg.generated
     */
    public void setShidu(String shidu) {
        this.shidu = shidu == null ? null : shidu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_datatitle.pm25
     *
     * @return the value of yx_ccyw_weather_datatitle.pm25
     *
     * @mbg.generated
     */
    public Integer getPm25() {
        return pm25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_datatitle.pm25
     *
     * @param pm25 the value for yx_ccyw_weather_datatitle.pm25
     *
     * @mbg.generated
     */
    public void setPm25(Integer pm25) {
        this.pm25 = pm25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_datatitle.pm10
     *
     * @return the value of yx_ccyw_weather_datatitle.pm10
     *
     * @mbg.generated
     */
    public Integer getPm10() {
        return pm10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_datatitle.pm10
     *
     * @param pm10 the value for yx_ccyw_weather_datatitle.pm10
     *
     * @mbg.generated
     */
    public void setPm10(Integer pm10) {
        this.pm10 = pm10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_datatitle.quality
     *
     * @return the value of yx_ccyw_weather_datatitle.quality
     *
     * @mbg.generated
     */
    public String getQuality() {
        return quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_datatitle.quality
     *
     * @param quality the value for yx_ccyw_weather_datatitle.quality
     *
     * @mbg.generated
     */
    public void setQuality(String quality) {
        this.quality = quality == null ? null : quality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_datatitle.wendu
     *
     * @return the value of yx_ccyw_weather_datatitle.wendu
     *
     * @mbg.generated
     */
    public String getWendu() {
        return wendu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_datatitle.wendu
     *
     * @param wendu the value for yx_ccyw_weather_datatitle.wendu
     *
     * @mbg.generated
     */
    public void setWendu(String wendu) {
        this.wendu = wendu == null ? null : wendu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yx_ccyw_weather_datatitle.ganmao
     *
     * @return the value of yx_ccyw_weather_datatitle.ganmao
     *
     * @mbg.generated
     */
    public String getGanmao() {
        return ganmao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yx_ccyw_weather_datatitle.ganmao
     *
     * @param ganmao the value for yx_ccyw_weather_datatitle.ganmao
     *
     * @mbg.generated
     */
    public void setGanmao(String ganmao) {
        this.ganmao = ganmao == null ? null : ganmao.trim();
    }
}